#idempiereEnv.properties
#Fri Jul 18 11:00:34 CEST 2025
ADEMPIERE_DB_SERVER=localhost
ADEMPIERE_APPS_SERVER=0.0.0.0
ADEMPIERE_DB_VERSION=2024-12-24
ADEMPIERE_FTP_PASSWORD=user@host.com
IDEMPIERE_JAVA_OPTIONS=
ADEMPIERE_KEYSTORECODEALIAS=idempiere
ADEMPIERE_DATE_VERSION=2024-12-24
ADEMPIERE_DB_NAME=idempiere-mo
JAVA_HOME=/usr/lib/jvm/jdk-17.0.11
ADEMPIERE_DB_USER=adempiere
ADEMPIERE_MAIN_VERSION=Release 12
ADEMPIERE_DB_EXISTS=Y
ADEMPIERE_MAIL_SERVER=localhost
ADEMPIERE_KEYSTOREWEBALIAS=idempiere
ADEMPIERE_DB_URL=jdbc\:postgresql\://localhost\:5432/idempiere-mo
ADEMPIERE_KEYSTORE=/home/luisamesty/sources/iDempiere12/idempiere/jettyhome/etc/keystore
ADEMPIERE_WEB_PORT=8080
ADEMPIERE_MAIL_USER=
ADEMPIERE_DB_PATH=postgresql
ADEMPIERE_FTP_SERVER=localhost
ADEMPIERE_WEB_ALIAS=localhost
ADEMPIERE_MAIL_UPDATED=
ADEMPIERE_ADMIN_EMAIL=
ADEMPIERE_KEYSTOREPASS=OBF\:1uh41zly1qw01vu11ym71ym71vv91qxq1zlk1ugm
ADEMPIERE_FTP_USER=anonymous
ADEMPIERE_SSL_PORT=8443
ADEMPIERE_DB_PORT=5432
ADEMPIERE_FTP_PREFIX=my
ADEMPIERE_DB_TYPE=PostgreSQL
IDEMPIERE_HOME=/home/luisamesty/sources/iDempiere12/idempiere
