#Adempiere
#Sat Jan 13 09:04:57 CET 2024
CDate=xyz2024-01-11 09\:53\:30.43
Warning=Do_not_change_any_of_the_data_as_they_will_have_undocumented_side_effects.
WarningD=Einstellungen_nicht_aendern,_da_diese_undokumentierte_Nebenwirkungen_haben.
UITheme=xyzAdempiere Theme
StorePassword=xyzN
AutoCommit=xyzY
ShowAcct=xyzY
Language=xyzes_ES
TraceFile=xyzN
CacheWindow=xyzY
PrintPreview=xyzN
ValidateConnectionOnStartup=xyzN
UILookFeel=xyzAdempiere
ShowTrl=xyzN
TempDir=xyz/tmp
AutoNew=xyzN
ApplicationUserID=xyzGardenAdmin
LoadTabMetaDataBackground=xyzN
SingleInstancePerWindow=xyzN
Connection=xyzCConnection[name\=0.0.0.0{localhost-idempiereLP11pro-adempiere},AppsHost\=0.0.0.0,WebPort\=8080,SSLPort\=8443,type\=PostgreSQL,DBhost\=localhost,DBport\=5433,DBname\=idempiereLP11pro,BQ\=false,FW\=false,FWhost\=,FWport\=0,UID\=adempiere]
Charset=xyzUTF-8
DataSource=xyzjava\:adempiereDB
OpenWindowMaximized=xyzN
AutoLogin=xyzN
AdempiereSys=xyzN
TraceLevel=xyzWARNING
LogMigrationScript=xyzN
