#idempiereEnv.properties
#Sat Jun 10 13:35:43 CEST 2023
ADEMPIERE_DB_SERVER=localhost
ADEMPIERE_APPS_SERVER=0.0.0.0
ADEMPIERE_DB_VERSION=2020-12-20
ADEMPIERE_FTP_PASSWORD=user@host.com
IDEMPIERE_JAVA_OPTIONS=-Xms64M -Xmx512M
ADEMPIERE_KEYSTORECODEALIAS=idempiere
ADEMPIERE_DATE_VERSION=2020-12-20
ADEMPIERE_DB_NAME=idempiereMCC8.2pro
JAVA_HOME=/usr/lib/jvm/jdk-11.0.2
ADEMPIERE_DB_USER=adempiere
ADEMPIERE_MAIN_VERSION=Release 8.2
ADEMPIERE_DB_EXISTS=Y
ADEMPIERE_MAIL_SERVER=localhost
ADEMPIERE_KEYSTOREWEBALIAS=idempiere
ADEMPIERE_DB_URL=jdbc\:postgresql\://localhost\:5432/idempiereMCC8.2pro
ADEMPIERE_KEYSTORE=/home/luisamesty/sources/iDempiere8.2/idempiere/jettyhome/etc/keystore
ADEMPIERE_WEB_PORT=8080
ADEMPIERE_MAIL_USER=
ADEMPIERE_DB_PATH=postgresql
ADEMPIERE_FTP_SERVER=localhost
ADEMPIERE_WEB_ALIAS=ubuntumini
ADEMPIERE_MAIL_UPDATED=
ADEMPIERE_ADMIN_EMAIL=
ADEMPIERE_KEYSTOREPASS=OBF\:1uh41zly1qw01vu11ym71ym71vv91qxq1zlk1ugm
ADEMPIERE_FTP_USER=anonymous
ADEMPIERE_SSL_PORT=8443
ADEMPIERE_DB_PORT=5432
ADEMPIERE_FTP_PREFIX=my
ADEMPIERE_DB_TYPE=PostgreSQL
IDEMPIERE_HOME=/home/luisamesty/sources/iDempiere8.2/idempiere
